  hold_low_low_true_low_low: -0.1,
  hold_low_low_true_low_medium: -0.2,
  hold_low_low_true_low_max: -0.3,
  hold_low_low_true_medium_low: -0.4,
  hold_low_low_true_medium_medium: -0.5,
  hold_low_low_true_medium_max: -0.6,
  hold_low_low_true_max_low: -0.7,
  hold_low_low_true_max_medium: -0.8,
  hold_low_low_true_max_max: -0.9,

  hold_low_high_true_low_low: -0.1,
  hold_low_high_true_low_medium: -0.2,
  hold_low_high_true_low_max: -0.3,
  hold_low_high_true_medium_low: -0.4,
  hold_low_high_true_medium_medium: -0.5,
  hold_low_high_true_medium_max: -0.6,
  hold_low_high_true_max_low: -0.7,
  hold_low_high_true_max_medium: -0.8,
  hold_low_high_true_max_max: -0.9,

  hold_high_low_true_low_low: -0.1,
  hold_high_low_true_low_medium: -0.2,
  hold_high_low_true_low_max: -0.3,
  hold_high_low_true_medium_low: -0.4,
  hold_high_low_true_medium_medium: -0.5,
  hold_high_low_true_medium_max: -0.6,
  hold_high_low_true_max_low: -0.7,
  hold_high_low_true_max_medium: -0.8,
  hold_high_low_true_max_max: -0.9,

  hold_high_high_true_low_low: -0.1,
  hold_high_high_true_low_medium: -0.2,
  hold_high_high_true_low_max: -0.3,
  hold_high_high_true_medium_low: -0.4,
  hold_high_high_true_medium_medium: -0.5,
  hold_high_high_true_medium_max: -0.6,
  hold_high_high_true_max_low: -0.7,
  hold_high_high_true_max_medium: -0.8,
  hold_high_high_true_max_max: -0.9,

  // Add more keys for combinations with extroverted = false

  hold_low_low_false_low_low: -0.1,
  hold_low_low_false_low_medium: -0.2,
  hold_low_low_false_low_max: -0.3,
  hold_low_low_false_medium_low: -0.4,
  hold_low_low_false_medium_medium: -0.5,
  hold_low_low_false_medium_max: -0.6,
  hold_low_low_false_max_low: -0.7,
  hold_low_low_false_max_medium: -0.8,
  hold_low_low_false_max_max: -0.9,

  hold_low_high_false_low_low: -0.1,
  hold_low_high_false_low_medium: -0.2,
  hold_low_high_false_low_max: -0.3,
  hold_low_high_false_medium_low: -0.4,
  hold_low_high_false_medium_medium: -0.5,
  hold_low_high_false_medium_max: -0.6,
  hold_low_high_false_max_low: -0.7,
  hold_low_high_false_max_medium: -0.8,
  hold_low_high_false_max_max: -0.9,

  hold_high_low_false_low_low: -0.1,
  hold_high_low_false_low_medium: -0.2,
  hold_high_low_false_low_max: -0.3,
  hold_high_low_false_medium_low: -0.4,
  hold_high_low_false_medium_medium: -0.5,
  hold_high_low_false_medium_max: -0.6,
  hold_high_low_false_max_low: -0.7,
  hold_high_low_false_max_medium: -0.8,
  hold_high_low_false_max_max: -0.9,

  hold_high_high_false_low_low: -0.1,
  hold_high_high_false_low_medium: -0.2,
  hold_high_high_false_low_max: -0.3,
  hold_high_high_false_medium_low: -0.4,
  hold_high_high_false_medium_medium: -0.5,
  hold_high_high_false_medium_max: -0.6,
  hold_high_high_false_max_low: -0.7,
  hold_high_high_false_max_medium: -0.8,
  hold_high_high_false_max_max: -0.9,